spring:
  application:
    name: kafka-streams-revenue-optimizer
  kafka:
    bootstrap-servers: localhost:29092
    streams:
      application-id: kafka-streams-revenue-optimizer
      properties:
        default:
          key.serde: org.apache.kafka.common.serialization.Serdes$LongSerde

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    org.apache.kafka: WARN
    com.gliaci: INFO

revenue-optimizer:
  kafka:
    topics:
      exchange-rates: "mysql-masterdata-EXCHANGE_RATE"
      orders: "orders"
      provider-codes: "provider-codes"
      optimized-orders: "optimized-orders"
